version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
    ports:
      - 5432:5432
    env_file:
      - ./db.env

  app:
    build:
      context: ./services/spring-boot
    command: java -jar eventik-rest-api-0.0.1-SNAPSHOT.jar
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

  nginx:
    build:
      context: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data:

