version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
    ports:
      - 5432:5432
    env_file:
      - ./db.env

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  app:
    build: ./services/spring-boot
    restart: unless-stopped
    depends_on:
      - db
      - rabbit

  nginx:
    build:
      context: ./services/nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data: